### ISSUE TITLE
Add profile to Docker 1.13

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/docker-bench#10]
Create a profile to Docker 1.13. The profile should be based on the Docker 17.06 profile, with the following changes:

Changes from docker 17.06

Remove 
2.18

Change:
2.1 - change name to "Restrict network traffic between containers (Scored) "
Move 2.15 -> 2.18
Move 2.16 -> 2.20
Move 2.17 -> 2.21

Move 6.1 to 6.4 and change name to "Avoid image sprawl (Not Scored)"
Move 6.2 to 6.5 and change name to "Avoid container sprawl (Not Scored) "

Add from the attached docker 1.13 cis benchmark:
2.15- Do not enable swarm mode, if not needed (Scored)
2.19 - Encrypt data exchanged between containers on different nodes on the overlay network (Scored) 
6.1 - Perform regular security audits of your host system and containers (Not Scored) 
6.2 - Monitor Docker containers usage, performance and metering (Not Scored) 
6.3 - Backup container data (Not Scored)

**Comment by jerbia** [comment]
Nii Nai, is this still relevant? I see that 2.16 and 2.17 were implemented
in the 1.13 profile. Is it missing in the other profiles?

**Comment by ttousai** [comment]
@jerbia no this is no longer relevant.

**Comment by liranaqua** [comment]
Description of the following checks should be changed to-

2.2 Set the logging level (Scored)
2.3 Allow Docker to make changes to iptables (Scored)
2.4 Do not use insecure registries (Scored)
2.5 Do not use the aufs storage driver (Scored)
2.6 Configure TLS authentication for Docker daemon (Scored)
2.7 Set default ulimit as appropriate (Not Scored)
2.9 Confirm default cgroup usage (Scored)
2.10 Do not change base device size until needed (Scored)
2.11 Use authorization plugin (Scored)
2.12 Configure centralized and remote logging (Scored)
2.13 Disable operations on legacy registry (v1) (Scored)
2.14 Enable live restore (Scored)
2.18 Disable Userland Proxy (Scored)
2.20 Apply a daemon-wide custom seccomp profile, if needed (Not Scored)
2.21 Avoid experimental features in production (Scored)

**Comment by lizrice** [comment]
@liranaqua with #14 merged do we think this is done?

**Comment by liranaqua** [comment]
yes, this issue is done

**Comment by lizrice** [comment]
closed with #14
