### ISSUE TITLE
While Running docker bench , it fails with weird error

### ISSUE THREAD

**Issue by ICDS-Offering** [aquasecurity/docker-bench#30]
./docker-bench --version 1.13.0
error converting 5.36870912e+08: strconv.Atoi: parsing "5.36870912e+08": invalid syntax

Can you suggest ?

**Comment by lizrice** [comment]
This is caused by https://github.com/aquasecurity/bench-common/issues/5

**Comment by lizrice** [comment]
Fixed by https://github.com/aquasecurity/bench-common/pull/33
