### ISSUE TITLE
Docker Swarm error even if no Docker Swarm installed.

### ISSUE THREAD

**Issue by amitaqua** [aquasecurity/docker-bench#61]
Hi Team,
When docker-bench runs - it will try and detect if Docker Swarm exists and if not it will print an error such as:

dockerd-current: time="2020-04-02T18:19:01.654114156+11:00" level=error msg="Error retrieving swarm unlock key" error="This node is not a swarm ma
nager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."

This is printed into /var/log/messages and can confuse the users who might think they have an issue with Docker.

Maybe if 'Docker Swarm' does not exists - simply skip that test or at least skip that message being printed?

**Comment by amitaqua** [comment]
Hi Team, the customer is getting alerts whenever an 'error' is printed in their /var/log/messages - so getting such a message every time the docker-bench run is not good for them.
Please advise if such a message can be printed ONLY if there is a real issue with Docker Swarm?

**Comment by amitaqua** [comment]
Hi Team - any update on this one?

**Comment by lizrice** [comment]
One option would be to edit the config file in this situation to skip the tests in section 7 if it's known they are not relevant
