### ISSUE TITLE
Find a bug: app.go [line:96]

### ISSUE THREAD

**Issue by liyilun1994** [aquasecurity/docker-bench#75]
// getDockerVersion returns the docker server engine version.
func getDockerVersion() (string, error) {
	cmd := exec.Command("docker", "version", "-f", "{{.Server.Version}}")
	out, err := cmd.Output()
	return string(out), err  //out is 18.09\n
}

modify:
// getDockerVersion returns the docker server engine version.
func getDockerVersion() (string, error) {
	cmd := exec.Command("docker", "version", "-f", "{{.Server.Version}}")
	out, err := cmd.Output()
	return strings.Replace(string(out), "\n", -1), err
}

**Comment by yoavrotems** [comment]
Hey, Could you elaborate please?
 And you can write a PR about it ! :) 
https://github.com/aquasecurity/docker-bench#contributing

**Comment by liyilun1994** [comment]
> Hey, Could you elaborate please?
> And you can write a PR about it ! :)
> https://github.com/aquasecurity/docker-bench#contributing


Hi, yoavrotems :
   Thanks for your Re. ,
   I will describe thequestion as follows:
   My ENV:
      Go version: 1.14.4
      Os: Centos7
 When call the function `func app(cmd *cobra.Command, args []string())`  and don't set variable `dockerVersion`,I got a error like this: "stat /etc/docker-cis/cfg/18.09
/definitions.yaml: no such file or directory" Although this file exists.
And I found the function named `getDockerVersion` return a string like `18.09\n`, when use method `filepath.join` to get abs. file path, the file path like this: "/etc/docker-cis/cfg/18.09\n/definitions.yaml, so can't found this file and load config failed。

So, We should handle the special character -- "\n", when the function `getDockerVersion`  returned.:)

**Comment by liyilun1994** [comment]
> Hey, Could you elaborate please?
> And you can write a PR about it ! :)
> https://github.com/aquasecurity/docker-bench#contributing

Hi, yoavrotems :
   Thanks for your Re. 
   I will describe the question as follows:
   My ENV:
       Go version: 1.14.4
       Os: Centos7
   Problem Describe: [filename: app.go]
       When call the function func `app(cmd *cobra.Command, args []string())` and don't set variable `dockerVersion`,I got a error like this:
 "stat /etc/docker-cis/cfg/18.09
/definitions.yaml: no such file or directory"
Although this file exists.And I found the function named `getDockerVersion` return a string like "18.09\n". When use method `filepath.join` to get a file path(the file path like this: "/etc/docker-cis/cfg/18.09\n/definitions.yaml"), process can't found this file and load config failed。

So, We should handle the special character `\n`, when the function `getDockerVersion` returned.:)

This is my modify：

import (
       "strings"
       ...
)
...
// getDockerVersion returns the docker server engine version.
func getDockerVersion() (string, error) {
    cmd := exec.Command("docker", "version", "-f", "{{.Server.Version}}")
    out, err := cmd.Output()
    return strings.Replace(string(out), "\n", -1), err
}

**Comment by yoavrotems** [comment]
Thank you @liyilun1994  !
