### ISSUE TITLE
If we are using Kubernetes, do we still need to run this tool to check if our Docker is compliant?

### ISSUE THREAD

**Issue by daxin09pp** [aquasecurity/docker-bench#91]
If we are using Kubernetes, do we still need to run this tool to check if our Docker is compliant?
Thanks!

**Comment by yoavrotems** [comment]
First thing what do you mean by **need** ?
If you have Docker installed its recommend to configure it in the best way - security speaking. 
If you only use Kubernetes then maybe just consider to uninstall Docker?

**Comment by yoavrotems** [comment]
I'm closing this issue, if you still have questions please reopen it. 
Thanks,
