### ISSUE TITLE
"test_number": "5.4" Include container name rather than container ID?

### ISSUE THREAD

**Issue by akshaya835** [aquasecurity/docker-bench#94]
It would be better suited to include container name than ID - makes it much easier to pickup which containers/apps are running as privileged

So for 5.4 Change audit command from:
"docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}:Privileged={{ .HostConfig.Privileged }}'",

to:
 "docker ps --quiet --all | xargs docker inspect --format '{{ .Name  }}:Privileged={{ .HostConfig.Privileged }}'",

**Comment by yoavrotems** [comment]
Hey thanks for opening an issue, we take the tests from CIS benchmark, https://github.com/aquasecurity/docker-bench#cis-docker-benchmark-support (Here you can see the links) 
We try as possible not to change the tests especially if it works as it should. 
So I'm closing this issue, if you believe using .Name would be better you are welcome to open a ticket to CIS
